/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';

export default function Model(props: any) {
  const group = useRef();
  // tslint:disable-next-line
  const { nodes, materials } = useGLTF('/green2.gltf') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ZBrush_defualt_group.geometry}
        material={materials['Material.002']}
        position={[0, 0.35, 0]}
      />
    </group>
  );
}

useGLTF.preload('/green2.gltf');
